# Generated by Django 2.2.2 on 2019-06-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_pair', models.CharField(max_length=100)),
                ('buy1', models.CharField(max_length=100)),
                ('buy2', models.CharField(max_length=100)),
                ('buy3', models.CharField(max_length=100)),
                ('buy4', models.CharField(max_length=100)),
                ('buy5', models.CharField(max_length=100)),
                ('sell1', models.CharField(max_length=100)),
                ('sell2', models.CharField(max_length=100)),
                ('sell3', models.CharField(max_length=100)),
                ('sell4', models.CharField(max_length=100)),
                ('sell5', models.CharField(max_length=100)),
                ('average', models.CharField(max_length=100)),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuisong.SiteConfig')),
            ],
        ),
    ]
